version: "3.9"
services:
  idrac-snmp-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idrac-snmp-exporter
    image: roemer/idrac-snmp-exporter:latest
    ports:
      - 8080:8080/tcp
    environment:
      - METRICS_PREFIX=idrac_
