name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: prom/snmp-generator:v0.20.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate
        run: /go/bin/generator generate
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: snmp.yml
