name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: prom/snmp-generator:v0.20.0

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: ./generator generate
